name: Deploy with Kamal

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H apps.rubymonstas.ch >> ~/.ssh/known_hosts

      - name: Install Ruby and Kamal
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Kamal
        run: gem install kamal

      - name: Set up Docker build
        uses: docker/setup-buildx-action@v2

      - name: Deploy with Kamal
        env:
          RAILS_ENV: production
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          KAMAL_REGISTRY_USERNAME: starshrimp
          KAMAL_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          kamal deploy
